### ISSUE TITLE
I cant run my test sh script

### ISSUE THREAD

**Issue by bgaines36** [bgaines36/Apache2#1]
Right now im not able to execute the simple script. Ive moved the file to another directory containing my docker compose file and now after executing its saying I dont have permission. I already tried changing ownership that didnt work.

**Comment by ranceforhiwd** [comment]
Test sample script works if you execute the script without  any spaces.  Example:
./nameOfScript.sh   (no spaces)

This will work.

**Comment by bgaines36** [comment]
wow it worked...thank you

**Comment by bgaines36** [comment]
After making a new file inside the container I ran the new test3.sh  and It worked after making it executable as the root user (+x test3.sh)
